import { useEffect } from 'react';
import * as XLSX from 'xlsx';

const coloniasData = [
  { nombres: "Andry de Jesús", apellidos: "Vanegas cuello", colonia: "" },
  { nombres: "Leonardo", apellidos: "Castillo", colonia: "" },
  { nombres: "Jeferson", apellidos: "Patiño", colonia: "" },
  { nombres: "Manuel", apellidos: "Bejarano", colonia: "" },
  { nombres: "Onaldis marías", apellidos: "Cardona Batista", colonia: "" },
  { nombres: "Mario Enrique", apellidos: "Alean Nuñez", colonia: "" },
  { nombres: "Gilberto Enrique", apellidos: "Villamil Lozano", colonia: "" },
  { nombres: "Carlos Alberto", apellidos: "Montaña Alvarado", colonia: "" },
  { nombres: "Samuel", apellidos: "Melo", colonia: "" },
  { nombres: "Patricia", apellidos: "Rodríguez", colonia: "" },
  { nombres: "Freider De Jesus", apellidos: "Atehortua Gallego", colonia: "" },
  { nombres: "Dagoberto", apellidos: "Villafañe", colonia: "" },
  { nombres: "Adalberto", apellidos: "Martinez", colonia: "" },
  { nombres: "Sonia Maria", apellidos: "Gallo Vega", colonia: "" },
  { nombres: "Carlos Leonardo", apellidos: "Boada castro", colonia: "" },
  { nombres: "Luis Carlos", apellidos: "Del Castillo Anaya", colonia: "" },
  { nombres: "Javier", apellidos: "Rodríguez", colonia: "" },
  { nombres: "Maikol", apellidos: "Zuleta", colonia: "" },
  { nombres: "Miguel angel", apellidos: "Zurita delgado", colonia: "" },
  { nombres: "jaime", apellidos: "Delgado meñoz", colonia: "" },
  { nombres: "Maria", apellidos: "Mosquera", colonia: "" },
  { nombres: "Carlos gregorio", apellidos: "Romero", colonia: "" },
  { nombres: "Marco ivan", apellidos: "Yanguas Tovar", colonia: "" },
  { nombres: "Jose Aron", apellidos: "Valencia", colonia: "" },
  { nombres: "Lo", apellidos: "Nsksk", colonia: "" },
  { nombres: "José Rafael", apellidos: "Carrillo", colonia: "" },
  { nombres: "Jhon", apellidos: "Arévalo Ruge", colonia: "" },
  { nombres: "Armando", apellidos: "Mancera", colonia: "" },
  { nombres: "Luz amparo", apellidos: "Tequia bailarin", colonia: "" },
  { nombres: "Pedro", apellidos: "Villamil", colonia: "" },
  { nombres: "Pedro", apellidos: "Bedoya", colonia: "" },
  { nombres: "Pablo", apellidos: "Mera", colonia: "" },
  { nombres: "Wilmer", apellidos: "Meza carreño", colonia: "" },
  { nombres: "Pedro", apellidos: "Tacue coque", colonia: "" },
  { nombres: "Jainer", apellidos: "galan", colonia: "" },
  { nombres: "Saida esther", apellidos: "Palacin padilla", colonia: "" },
  { nombres: "Tilso Rafael", apellidos: "Miranda", colonia: "" },
  { nombres: "Kevin jose", apellidos: "Lopez Acosta", colonia: "" },
  { nombres: "Bayron", apellidos: "Gómez", colonia: "" },
  { nombres: "jhilber", apellidos: "campo alonso", colonia: "" },
  { nombres: "Sergio Luis", apellidos: "Gutiérrez serpa", colonia: "" },
  { nombres: "José himberto", apellidos: "Arango grjales", colonia: "" },
  { nombres: "Maicol", apellidos: "Saez", colonia: "" },
  { nombres: "Luis Omar", apellidos: "Estrada C", colonia: "" },
  { nombres: "Neider enilson", apellidos: "Rojas Gamboa", colonia: "" },
  { nombres: "Manuel", apellidos: "Campuzano", colonia: "" },
  { nombres: "José Fabián", apellidos: "López astaiza", colonia: "" },
  { nombres: "Iban", apellidos: "Acosta", colonia: "" },
  { nombres: "Oswaldo", apellidos: "Gordillo", colonia: "" },
  { nombres: "Rodrigo", apellidos: "Ramirez Villegas", colonia: "" },
  { nombres: "Maikel", apellidos: "Corrales", colonia: "" },
  { nombres: "Asael", apellidos: "Sánchez", colonia: "" },
  { nombres: "Carlos", apellidos: "Rozo Torres", colonia: "" },
  { nombres: "James victor", apellidos: "Figueroa Silva", colonia: "" },
  { nombres: "Jeancarlos", apellidos: "Morales", colonia: "" },
  { nombres: "Juan Alberto", apellidos: "Sánchez Galván", colonia: "" },
  { nombres: "Wilson", apellidos: "Quisoboni", colonia: "" },
  { nombres: "Francisco", apellidos: "calle", colonia: "" },
  { nombres: "Jose Gabriel", apellidos: "Molina cortez", colonia: "" },
  { nombres: "Lorena", apellidos: "Cortes", colonia: "" },
  { nombres: "Hugo", apellidos: "Arias", colonia: "" },
  { nombres: "Pedro Antonio", apellidos: "Villasana Delgado", colonia: "" },
  { nombres: "Jose David", apellidos: "Lugo", colonia: "" },
  { nombres: "Jose edinson", apellidos: "Lopez prada", colonia: "" },
  { nombres: "Freddys", apellidos: "Mendoza", colonia: "" },
  { nombres: "Jesus david", apellidos: "Carmona", colonia: "" },
  { nombres: "Fredy sail", apellidos: "Perez vanole", colonia: "" },
  { nombres: "James", apellidos: "Rodrguez", colonia: "" },
  { nombres: "Dayana", apellidos: "Dayana", colonia: "" },
  { nombres: "Carlos", apellidos: "Calderón", colonia: "" },
  { nombres: "Cesar", apellidos: "Augusto", colonia: "" },
  { nombres: "Jose Luis", apellidos: "Falcon Martinez", colonia: "" },
  { nombres: "Maria", apellidos: "Betancur Osorio", colonia: "" },
  { nombres: "Cristian estiven", apellidos: "Lozano angulo", colonia: "" },
  { nombres: "Elías", apellidos: "Cantillo", colonia: "" },
  { nombres: "Néstor", apellidos: "González 3195723173", colonia: "" },
  { nombres: "Diego León", apellidos: "López Zapata", colonia: "" },
  { nombres: "José Fernando", apellidos: "Carvajal", colonia: "" },
  { nombres: "Deimer", apellidos: "Berrio", colonia: "" },
  { nombres: "Jorge Alfredo", apellidos: "Orozco Arbeláez", colonia: "" },
  { nombres: "Wilson", apellidos: "Galeano", colonia: "" },
  { nombres: "Angie Lizeth", apellidos: "Daza restrepo", colonia: "" },
  { nombres: "Iván eduardo", apellidos: "Carvajal cruz", colonia: "" },
  { nombres: "Armando enrique", apellidos: "Gutierrez. Guerrero", colonia: "" },
  { nombres: "Diego Ortega", apellidos: "Ortega Obando", colonia: "" },
  { nombres: "Jhonatan David", apellidos: "Martinez palacios", colonia: "" },
  { nombres: "Rafael", apellidos: "Sarate laguna", colonia: "" },
  { nombres: "Michelle", apellidos: "Méndez", colonia: "" },
  { nombres: "Pablo Emilio", apellidos: "Sánchez García", colonia: "" },
  { nombres: "William", apellidos: "Diaz machado", colonia: "" },
  { nombres: "Cristian", apellidos: "Califa", colonia: "" },
  { nombres: "Jose Orlando", apellidos: "Reina carrillo", colonia: "" },
  { nombres: "José", apellidos: "Polo", colonia: "" },
  { nombres: "Jorge", apellidos: "Imbaqui herrera", colonia: "Casa" },
  { nombres: "Yuly adriana", apellidos: "Rodriguez casallas", colonia: "Oficina de administración del centro comercial GRAN manzana" },
  { nombres: "Fabio", apellidos: "Escobar", colonia: "Casa" },
  { nombres: "Ronald", apellidos: "Rodríguez", colonia: "CAsa" },
  { nombres: "Alexander", apellidos: "Suarez castro", colonia: "Casa" },
  { nombres: "Alex", apellidos: "Gomes", colonia: "Casa" },
  { nombres: "Camilo", apellidos: "Amariles Grisales", colonia: "" },
  { nombres: "Nidian", apellidos: "Perez", colonia: "Casa" },
  { nombres: "Edwin", apellidos: "Puerto", colonia: "Casa amarilla de puertas verdes bolsa Palestina" },
  { nombres: "Luis ferney", apellidos: "Rojas osorio", colonia: "Barrio llantos guarala" },
  { nombres: "Taimer emiro", apellidos: "Torrado pacheco", colonia: "Al lado del parqueadero la 62" },
  { nombres: "Ariel", apellidos: "Pérez", colonia: "Casa apartamento 1" },
  { nombres: "Cristian David", apellidos: "Ramos Arriaga", colonia: "Casa 3 piso rosada" },
  { nombres: "Geomar", apellidos: "Quintero", colonia: "Leticia amazona" },
  { nombres: "Andrés ricardo", apellidos: "Robayo sarabia", colonia: "Casa" },
  { nombres: "José Antonio", apellidos: "Conde otero", colonia: "Casa cural o despacho parroquial" },
  { nombres: "Omar", apellidos: "Pineda", colonia: "" },
  { nombres: "Nelson", apellidos: "Granada", colonia: "Casa" },
  { nombres: "Juan Carlos", apellidos: "Acuña Cifuentes", colonia: "Local Huellas y Garras" },
  { nombres: "Víctor", apellidos: "Sanchez", colonia: "" },
  { nombres: "Johan", apellidos: "Gañan", colonia: "" },
  { nombres: "Oscar", apellidos: "Medellin", colonia: "Bloque 31 apto 262" },
  { nombres: "Ramiro jose", apellidos: "Barreto rivas", colonia: "Primer piso letra b" },
  { nombres: "Wuilme antonio", apellidos: "Granadillo riera", colonia: "Apartamento" },
  { nombres: "Miguel", apellidos: "Castrillon", colonia: "Casa 3 piso" },
  { nombres: "Johan", apellidos: "Torres", colonia: "Casa" },
  { nombres: "Cristian", apellidos: "Sánchez", colonia: "Apartamento" },
  { nombres: "Dumar", apellidos: "Herrera", colonia: "Apartamento 806" },
  { nombres: "Alexis", apellidos: "Diaz", colonia: "Droguería la mejor" },
  { nombres: "Balvina Isabel", apellidos: "Malo covo", colonia: "Conjunto 4 torre 24 apto 501 las gardenias" },
  { nombres: "Jhoyner", apellidos: "Lopera Jaramillo", colonia: "" },
  { nombres: "Nikol Jessenia", apellidos: "Ariza Gordillo", colonia: "Casa de rejas gris" },
  { nombres: "Karen", apellidos: "Piña", colonia: "Vía la iglesia" },
  { nombres: "DIEGO FERNANDO", apellidos: "CARO BALLESTEROS", colonia: "Piso 1 apto 103" },
  { nombres: "David", apellidos: "Guerra", colonia: "" },
  { nombres: "Andrés Felipe", apellidos: "Ramirez Valencia", colonia: "andpipr@gmail.com" },
  { nombres: "Heli", apellidos: "Bolaños", colonia: "Casa 13" },
  { nombres: "Jose danilo", apellidos: "Diaz Pérez", colonia: "Casa 215 manzana 8" },
  { nombres: "Luis", apellidos: "Impata", colonia: "Casa" },
  { nombres: "Miģuel antonio", apellidos: "Santos gomez", colonia: "Casa" },
  { nombres: "Daniel Fernando", apellidos: "baquiro Rocha", colonia: "Casa 2 piso" },
  { nombres: "Carlos Andrés", apellidos: "Vega navia", colonia: "Oficina interrapidisimo Dagua" },
  { nombres: "Killian Duvan", apellidos: "Ayala Pabon", colonia: "Casa" },
  { nombres: "Tomas", apellidos: "Hurtado", colonia: "Casa" },
  { nombres: "Guillermo Eduardo", apellidos: "Trujillo", colonia: "Dentro del Skype Park" },
  { nombres: "Kelvin jose", apellidos: "Román lopez", colonia: "Oficina" },
  { nombres: "Arturo", apellidos: "Silva", colonia: "Torre 3 apto 802 Xie conjunto residencial" },
  { nombres: "Raul Fredy", apellidos: "Holguin Vasquez", colonia: "Interior 1. Apto 412" },
  { nombres: "José David", apellidos: "Leguizamo Hernández Leguizamo", colonia: "Casa esquinera" },
  { nombres: "Marlon", apellidos: "Palma", colonia: "Enfrente de nuevo sol" },
  { nombres: "Gabriela", apellidos: "Silva", colonia: "" },
  { nombres: "Santiago", apellidos: "De los reyes", colonia: "Esquina" },
  { nombres: "JUAN", apellidos: "BALLEN", colonia: "Casa" },
  { nombres: "Cristian", apellidos: "Arenas", colonia: "Parques de modelia" },
  { nombres: "John Fredy", apellidos: "Aponte Sepúlveda", colonia: "apartamento 401" },
  { nombres: "Carlos", apellidos: "Ortegón usa", colonia: "Casa" },
  { nombres: "Diego nicolas", apellidos: "Rodríguez vera", colonia: "Casa primer piso" },
  { nombres: "Brayan", apellidos: "Silva", colonia: "Paz deariporo" },
  { nombres: "Antonio Ramón", apellidos: "Alvarenga Rodríguez", colonia: "antonioalvarenga21@gmail.com" },
  { nombres: "Ramiro", apellidos: "Sepulveda Montalvo", colonia: "Casa" },
  { nombres: "Jhon janer", apellidos: "López nieva", colonia: "Casa" },
  { nombres: "Carlos", apellidos: "Alfonso", colonia: "Casa" },
  { nombres: "David Stiwar", apellidos: "Marmolejo", colonia: "Obapo sector las villas" },
  { nombres: "Deivi", apellidos: "Moreno", colonia: "Oficina" },
  { nombres: "Alvaro José", apellidos: "Neira Gallo", colonia: "Casa" },
  { nombres: "Lina Marcela", apellidos: "Molano Urrego", colonia: "" },
  { nombres: "Juan Carlos", apellidos: "De La Rosa", colonia: "casa de rejas blancas" },
  { nombres: "jhonatan Ferney", apellidos: "Beltrán Hernández", colonia: "apt 303" },
  { nombres: "Katherine", apellidos: "Alvarado", colonia: "Edificio Boston Plaza" },
  { nombres: "Jhon neider", apellidos: "Velasquez genes", colonia: "Remedio antioquia" },
  { nombres: "Miguel", apellidos: "Hernández", colonia: "Casa de color amarillo en la parte inferior" },
  { nombres: "Virnoz", apellidos: "Soto Ramírez", colonia: "Casa quinta" },
  { nombres: "Maicol Smith", apellidos: "Cuellar España", colonia: "Interrrapidisimo Acevedo Huila" },
  { nombres: "Benjamin", apellidos: "Castillo", colonia: "Torre 6 apartamento 3123 manzana 3a" },
  { nombres: "Elias", apellidos: "Zabaleta", colonia: "Casa" },
  { nombres: "Juan Carlos", apellidos: "Gutiérrez", colonia: "Casa 10 Metropolitano del norte" },
  { nombres: "Jairo Antonio", apellidos: "Sánchez Arenas", colonia: "Torre 9 apto 601" },
  { nombres: "Maicol", apellidos: "Perdomo garcia", colonia: "" },
  { nombres: "carlos ivan", apellidos: "tonkon sanabria", colonia: "" },
  { nombres: "Juan David", apellidos: "Torres Acero", colonia: "Casa" },
  { nombres: "Armando", apellidos: "Rodríguez culman", colonia: "Tienda esquinera" },
  { nombres: "Anderson", apellidos: "Beltran", colonia: "Portería" },
  { nombres: "Juan", apellidos: "Fernández", colonia: "Casa" },
  { nombres: "Jorge", apellidos: "Santacruz", colonia: "" },
  { nombres: "Alvaro", apellidos: "Galindo Suarez", colonia: "Local floristeria" },
  { nombres: "Yeison", apellidos: "Ceballos", colonia: "Casa" },
  { nombres: "Edilberto", apellidos: "Carmona Muñoz", colonia: "" },
  { nombres: "Nohora", apellidos: "Lopez", colonia: "Casa" },
  { nombres: "Jorge Yovani", apellidos: "Llanten", colonia: "Bodega" },
  { nombres: "Jhon alexander", apellidos: "Perez. Ruiz", colonia: "" },
  { nombres: "Miller alexander", apellidos: "Cerdas hernandez", colonia: "Apt 302" },
  { nombres: "Francy", apellidos: "Garzon", colonia: "" },
  { nombres: "JHONATAN", apellidos: "RODRIGUEZ", colonia: "" },
  { nombres: "Marlon", apellidos: "Herrera López", colonia: "Antirrapidisimo" },
  { nombres: "Gloria María", apellidos: "Castrillon Peláez", colonia: "Casa" },
  { nombres: "Andres", apellidos: "Gonzalez", colonia: "Cedritos" },
  { nombres: "Julio Cesar", apellidos: "Yépez Espitia", colonia: "Casa" },
  { nombres: "Yaquelin", apellidos: "Ordóñez Burbano", colonia: "Stx sports" },
  { nombres: "Arcenio", apellidos: "Camayo yandy", colonia: "Oficina inter rapidisimo" },
  { nombres: "Guillermo", apellidos: "Alzate Valencia", colonia: "Casa" },
  { nombres: "Alejandro", apellidos: "Duque", colonia: "Torre 7 apartamento 601" },
  { nombres: "Reinaldo", apellidos: "Bermeo", colonia: "Casa" },
  { nombres: "Herminsul", apellidos: "Robayo gonzalez", colonia: "Casa" },
  { nombres: "Evelin", apellidos: "Guerra", colonia: "Casa" },
  { nombres: "César Augusto", apellidos: "Salcedo acosta", colonia: "" },
  { nombres: "Jesús anivar", apellidos: "López Enríquez", colonia: "Casa" },
  { nombres: "Rafael Antonio", apellidos: "Díaz Pinto", colonia: "Apartamento" },
  { nombres: "Jose", apellidos: "López Hernández", colonia: "Casa" },
  { nombres: "Paula Andrea", apellidos: "Montoya sarmiento de", colonia: "" },
  { nombres: "Jose", apellidos: "Leon", colonia: "" },
  { nombres: "Cesar Alfonso", apellidos: "Solarte Vargas", colonia: "" },
  { nombres: "Luis Fernando", apellidos: "olaya vargas", colonia: "Torre 2 APT 502" },
  { nombres: "Sergio", apellidos: "Palacios Vargas", colonia: "Casa 8" },
  { nombres: "David", apellidos: "Vasquez villegas", colonia: "Apartamento tercer piso" },
  { nombres: "Gabriela", apellidos: "Durán", colonia: "" },
  { nombres: "Édgar", apellidos: "Pérez", colonia: "Casa segundo" },
  { nombres: "Jaime", apellidos: "Ruiz henao", colonia: "Casa" },
  { nombres: "Edgar", apellidos: "Perez", colonia: "Casa de 2 pisos" },
  { nombres: "John Alexander", apellidos: "Calderon chacon", colonia: "" },
  { nombres: "Anderson", apellidos: "Heredia Poveda", colonia: "Torre 8 apto 501 - torres del Diamante" },
  { nombres: "Sandra", apellidos: "Pasuy", colonia: "Oficina principal" },
  { nombres: "Cesar", apellidos: "Otalvaro", colonia: "" },
  { nombres: "Sandra Patricia", apellidos: "Granada Acuña", colonia: "Bloque 32 apartamento 103" },
  { nombres: "Joselin", apellidos: "Alarcon Torres", colonia: "" },
  { nombres: "Daniel Antonio", apellidos: "Betancourt prieto", colonia: "Casa" },
  { nombres: "Juan alexis", apellidos: "Mahecha ortiz", colonia: "Casa" },
  { nombres: "Cesar alonzo", apellidos: "Martines rivera", colonia: "" },
  { nombres: "Silvio", apellidos: "Patiño", colonia: "raptigre3220@gmail.com" },
  { nombres: "Jose", apellidos: "Mata", colonia: "Los cerezos sector las margaritas mz c lote 5" },
  { nombres: "Lina Rosa", apellidos: "Beleño López", colonia: "Casa tercer piso" },
  { nombres: "Hugo", apellidos: "Chavez", colonia: "Marroquin 2" },
  { nombres: "José Rodolfo", apellidos: "Calderón Rodríguez", colonia: "Local lavadero" },
  { nombres: "Yoly", apellidos: "Saavedra", colonia: "Restaurante" },
  { nombres: "John Alexander", apellidos: "Contreras muñoz", colonia: "" },
  { nombres: "Juan Carlos", apellidos: "Gutierrez", colonia: "Casa 10" },
  { nombres: "Yoselin", apellidos: "Lovera", colonia: "Barrio Sam Nicolás" },
  { nombres: "Juan", apellidos: "Oliveros", colonia: "Casa" },
  { nombres: "Carlos alberto", apellidos: "Dominguez robayo", colonia: "Casa apartamento" },
  { nombres: "Yeison", apellidos: "Rangel", colonia: "Local" },
  { nombres: "Harold", apellidos: "Sanchez", colonia: "Casa naranja 4 pisos" },
  { nombres: "Sayuri", apellidos: "Ahumada herrera", colonia: "Torre 1 apto 1004" },
  { nombres: "Nurys", apellidos: "Romro", colonia: "" },
  { nombres: "Laura daniela", apellidos: "Arias", colonia: "Segundo piso apartamento 202" },
  { nombres: "Santiago", apellidos: "Vanegas Hernández", colonia: "San Antonio Alto" },
  { nombres: "Jefferson", apellidos: "Becerra", colonia: "Casa frente a la estación de Transmilenio Bosa estación" },
  { nombres: "Jhon faiver", apellidos: "Espinosa benjumea", colonia: "Hotel Morichal" },
  { nombres: "Yohendry jesus", apellidos: "Cobis camacaro", colonia: "Finca" },
  { nombres: "Anderson", apellidos: "Agudelo", colonia: "" },
  { nombres: "Hernan", apellidos: "Epiayu", colonia: "" },
  { nombres: "Luis Fernando", apellidos: "Jiménez Gomez", colonia: "" },
  { nombres: "David", apellidos: "Escobar", colonia: "" },
  { nombres: "Anthony Damián", apellidos: "Gómez Pastrano", colonia: "" },
  { nombres: "Deydi", apellidos: "Navarro", colonia: "" },
  { nombres: "Edinson andres", apellidos: "Castillo medina", colonia: "" },
  { nombres: "Hugo amin", apellidos: "Rojas vanegas", colonia: "" },
  { nombres: "Edicson Alfonso", apellidos: "Villota Bolaños", colonia: "" },
  { nombres: "Victor", apellidos: "Calderon", colonia: "" },
  { nombres: "Pablo", apellidos: "Coque", colonia: "" },
  { nombres: "Jhonier agnher", apellidos: "Orozco giraldo", colonia: "" },
  { nombres: "UBERNEY", apellidos: "GALEANO RESTREPO", colonia: "" },
  { nombres: "Margarita", apellidos: "Cera acosta", colonia: "" },
  { nombres: "Jesús dario", apellidos: "Renteria lemos", colonia: "" },
  { nombres: "Vanessa", apellidos: "Armenta montaño", colonia: "" },
  { nombres: "Alexander", apellidos: "Rendon londoño", colonia: "" },
  { nombres: "Oscar", apellidos: "Paba Luna", colonia: "" },
  { nombres: "Luis Enrique", apellidos: "Pascuas", colonia: "" },
  { nombres: "Geraldo antonio", apellidos: "Ruz Mendez", colonia: "" },
  { nombres: "Humberto", apellidos: "Ruiz", colonia: "" },
  { nombres: "Dainer Rafael", apellidos: "Castro Escorcia", colonia: "" },
  { nombres: "Luis Fabián", apellidos: "Nova perez", colonia: "" },
  { nombres: "Santiago", apellidos: "Vanegas", colonia: "" },
  { nombres: "Jesús Darío", apellidos: "Pérez angarita", colonia: "" },
  { nombres: "Yeferson", apellidos: "Jacobombaire", colonia: "Distribuidora blu barrio centro" },
  { nombres: "Yeison", apellidos: "Soto Vivas", colonia: "" },
  { nombres: "Cesar", apellidos: "Uribe", colonia: "" },
  { nombres: "John", apellidos: "Huérfano", colonia: "" },
  { nombres: "David", apellidos: "Tobar Garzon", colonia: "" },
  { nombres: "Adrian Alexander", apellidos: "Cardenas salinas", colonia: "" },
  { nombres: "Jean", apellidos: "Moreno", colonia: "" },
  { nombres: "Andrés", apellidos: "Muñoz", colonia: "" },
  { nombres: "Bairon", apellidos: "Orttiz", colonia: "" },
  { nombres: "Rubén Darío", apellidos: "Cabrera Robayo", colonia: "" },
  { nombres: "Edwin", apellidos: "Sanchez", colonia: "" },
  { nombres: "Angela", apellidos: "Cañola", colonia: "" },
  { nombres: "Heriberto", apellidos: "torres Pérez", colonia: "" },
  { nombres: "Gustavo Adolfo", apellidos: "Pérez Díaz", colonia: "Casa" },
  { nombres: "Yennifer", apellidos: "Reyes", colonia: "" },
  { nombres: "Jimmy", apellidos: "Morales", colonia: "" },
  { nombres: "Fabián Andrés", apellidos: "Moreno", colonia: "" },
  { nombres: "Karem", apellidos: "Arevalo", colonia: "" },
  { nombres: "Alexander", apellidos: "Pinto Galindo", colonia: "" },
  { nombres: "Juliana", apellidos: "Rangel", colonia: "" },
  { nombres: "Carlos enrique", apellidos: "Acosta cataño", colonia: "" },
  { nombres: "Eibar", apellidos: "Yugue claro", colonia: "" },
  { nombres: "Jose Epifanio", apellidos: "Ruiz Chaverra", colonia: "" },
  { nombres: "Rogers", apellidos: "Harrys", colonia: "" },
  { nombres: "milton", apellidos: "plaza", colonia: "" },
  { nombres: "Maria", apellidos: "Bernate", colonia: "" },
  { nombres: "Luis", apellidos: "Torres", colonia: "" },
  { nombres: "Victor", apellidos: "Galezo", colonia: "" },
  { nombres: "Reinaldo", apellidos: "Molina García", colonia: "" },
  { nombres: "Natalia", apellidos: "Torres", colonia: "" },
  { nombres: "giver", apellidos: "campo", colonia: "" },
  { nombres: "Jesús Manuel", apellidos: "López", colonia: "" },
  { nombres: "Jaime Andrés", apellidos: "Salamanca abella", colonia: "" },
  { nombres: "Carmen Elena", apellidos: "Mosquera Mosquera", colonia: "" },
  { nombres: "Estefany", apellidos: "Arciniegas cortes", colonia: "" },
  { nombres: "Elizabeth", apellidos: "Hurtado Murillo", colonia: "" },
  { nombres: "Miguel", apellidos: "Mejias Rodríguez", colonia: "" },
  { nombres: "Luz Marina", apellidos: "Castellanos", colonia: "" },
  { nombres: "Jhon Jairo", apellidos: "Salazar panche", colonia: "" },
  { nombres: "Alexandra del valle", apellidos: "Vasquez Gutierrez", colonia: "" },
  { nombres: "Juan", apellidos: "Muriel", colonia: "" },
  { nombres: "James", apellidos: "López Hernández", colonia: "" },
  { nombres: "Lia", apellidos: "Reyes", colonia: "" },
  { nombres: "Luis angel", apellidos: "Rivera Barragán", colonia: "" },
  { nombres: "Yuly", apellidos: "Barrera Barrera", colonia: "" },
  { nombres: "José Giovanni", apellidos: "Ortiz Ramírez", colonia: "" },
  { nombres: "Gabriela", apellidos: "Gonzales", colonia: "" },
  { nombres: "Olga Olga", apellidos: "Gil", colonia: "" },
  { nombres: "Jorge Alejandro", apellidos: "Parra", colonia: "" },
  { nombres: "Jose Herneido", apellidos: "Silva Gómez", colonia: "" },
  { nombres: "Alexander", apellidos: "Díaz olaya", colonia: "" },
  { nombres: "Iván Dario", apellidos: "Ruiz chavez", colonia: "" },
  { nombres: "Carlos enrique", apellidos: "Mesa", colonia: "" },
  { nombres: "LUIS CARLOS", apellidos: "PAI ERAZO", colonia: "" },
  { nombres: "Jesus Miguel", apellidos: "Campo Castaño", colonia: "" },
  { nombres: "Edgar ruben", apellidos: "Huertas chisco", colonia: "" },
  { nombres: "Eric Alexander", apellidos: "Malagón Ramirez", colonia: "" },
  { nombres: "Edward", apellidos: "Mazo", colonia: "" },
  { nombres: "Jose", apellidos: "Melendez", colonia: "" },
  { nombres: "Jhon", apellidos: "Cachimuel", colonia: "" },
  { nombres: "David", apellidos: "Jurado", colonia: "" },
  { nombres: "Johana", apellidos: "Rodríguez Sanabria", colonia: "" },
  { nombres: "CARLOS", apellidos: "ALZATE", colonia: "" },
  { nombres: "Stewin", apellidos: "Hurtado", colonia: "" },
  { nombres: "Oswaldo Alexander", apellidos: "Gonzalez Marin", colonia: "" },
  { nombres: "Marlon Jose", apellidos: "Montero Marquez", colonia: "Torre 5 Apto 1003" },
  { nombres: "Miguel Ángel", apellidos: "Torres Diaz", colonia: "Apto 202" },
  { nombres: "Alberto", apellidos: "Miranda", colonia: "Frente al club los trupillos barrio manzanares" },
  { nombres: "Maricela", apellidos: "Machado Rios", colonia: "" },
  { nombres: "sergio", apellidos: "garcía", colonia: "casa" },
  { nombres: "Abraham", apellidos: "Lopez", colonia: "La pajarera" },
  { nombres: "Andres", apellidos: "Duarte", colonia: "Cr39 #30-40 Sur" },
  { nombres: "Richard Alfonso", apellidos: "Arrieta torres", colonia: "richardarrieta2026@gmail.com" },
  { nombres: "María", apellidos: "Santos", colonia: "Barrio María Eugenia" },
  { nombres: "David estiven", apellidos: "Villa acosta", colonia: "Casa" },
  { nombres: "Maria", apellidos: "Cardenas", colonia: "Cada 1 piso" },
  { nombres: "Miguel", apellidos: "Castrillon", colonia: "Casa" },
  { nombres: "Heisen", apellidos: "Pulido Salamanca", colonia: "" },
  { nombres: "Yohany", apellidos: "Imbachi arias", colonia: "Torre 3 apartamento 201" },
  { nombres: "Jaime", apellidos: "Caucali", colonia: "" },
  { nombres: "Angelica María", apellidos: "Jaimes capacho", colonia: "Casa" },
  { nombres: "José Ramiro", apellidos: "Duque Román", colonia: "Casa" },
  { nombres: "Mauricio", apellidos: "Rodriguez", colonia: "Barrio los cedros" },
  { nombres: "Leonardo", apellidos: "Gutiérrez naranjo", colonia: "Casa" },
  { nombres: "John alexander", apellidos: "Uribe jimenez", colonia: "Palos y leños puentearanda" },
  { nombres: "JONATHAN", apellidos: "BOLAÑO CARVAJAL", colonia: "" },
  { nombres: "Giovanny", apellidos: "Villanueva mendez", colonia: "" },
  { nombres: "Omar Alonso", apellidos: "Roldan Giraldo", colonia: "" },
  { nombres: "Rubén dario", apellidos: "Berrio Gómez", colonia: "Entrando por surtimax" },
  { nombres: "Jorge", apellidos: "Imbaqui herrera", colonia: "Casa" },
  { nombres: "Wilfredo", apellidos: "Abril Cáceres", colonia: "Casa esquinera" },
  { nombres: "Karol", apellidos: "rodriguez Hidalgo", colonia: "Oficina interrapidisimo" },
  { nombres: "Edgardo", apellidos: "Campuzano", colonia: "Torre" },
  { nombres: "Ivan", apellidos: "Barragan", colonia: "Apartemento 1 piso" },
  { nombres: "Juan David", apellidos: "Lopez Cordoba", colonia: "Santa cruz" },
  { nombres: "Esteban", apellidos: "Gonzalez", colonia: "Planta de producción" },
  { nombres: "Angy", apellidos: "Tovar", colonia: "Parque norte" },
  { nombres: "Julieth", apellidos: "Pinto", colonia: "" },
  { nombres: "Oswaldo", apellidos: "quiloga", colonia: "Parqueadero" },
  { nombres: "Adriana", apellidos: "Pinilla", colonia: "Piso 4" },
  { nombres: "Luis Fernando", apellidos: "Rodríguez Charcas", colonia: "Casa esquina frente al coliseo" },
  { nombres: "Joan", apellidos: "Aguirre", colonia: "Organic segundo piso" },
  { nombres: "Elizabeth", apellidos: "Pelaez", colonia: "Casas" },
  { nombres: "Lisardo", apellidos: "Molina", colonia: "Casa" },
  { nombres: "Karen", apellidos: "Arrieta Escobar", colonia: "Casa 1 piso 1" },
  { nombres: "Vanesa", apellidos: "García", colonia: "Frente secretaria de tránsito" },
  { nombres: "Luis", apellidos: "Chavarro", colonia: "Casa" },
  { nombres: "Nelys", apellidos: "Arroyo teheran", colonia: "Apartamento trasero" },
  { nombres: "Jhonatan", apellidos: "Alvarez", colonia: "Apto 802" },
  { nombres: "Alexander", apellidos: "Quiroz", colonia: "Apto 301" },
  { nombres: "Víctor", apellidos: "Sanchez", colonia: "2 piso nueva castilla" },
  { nombres: "Jorge Armando", apellidos: "Gualteros Aguirre", colonia: "Torre 11 apto 104 conjunto residencial bosque de Bogotá 2" },
  { nombres: "Johan Stiven", apellidos: "Tejada Céspedes", colonia: "Torre 4 apartamento 402" },
  { nombres: "Jose Miguel", apellidos: "Piza", colonia: "17 apto 103" },
  { nombres: "Hiber", apellidos: "Osorio", colonia: "Casa" },
  { nombres: "José Gerardo", apellidos: "Soler Ramírez", colonia: "" },
  { nombres: "Daniel Andrés", apellidos: "Machuca diaz", colonia: "" },
  { nombres: "Hector de Jesús", apellidos: "Cantillo Sanchez", colonia: "Casa" },
  { nombres: "Emilson Manuel", apellidos: "López Pulido", colonia: "" },
  { nombres: "Daniel", apellidos: "Martinez", colonia: "" },
  { nombres: "Daniel", apellidos: "Vargas Contreras", colonia: "Casa" },
  { nombres: "Jose luis", apellidos: "Mesa", colonia: "Casa barrios unidos concepcion norte" },
  { nombres: "Johan", apellidos: "Benavides", colonia: "" },
  { nombres: "Luis daniel", apellidos: "Pallares mendoza", colonia: "Apartamento" },
  { nombres: "Daniel", apellidos: "Osorio llamas", colonia: "Conjunto cerrado san Francisco" },
  { nombres: "Juan Carlos", apellidos: "De Alba Solano", colonia: "Casa" },
  { nombres: "Carlos", apellidos: "Mesa Ríos", colonia: "Casa" },
  { nombres: "Luis Humberto", apellidos: "Arcos jimenez", colonia: "Casa" },
  { nombres: "Sandra", apellidos: "Ocampo", colonia: "Casa la Merced" },
  { nombres: "José Manuel", apellidos: "Torres Meneses", colonia: "Apto 606" },
  { nombres: "Bayron", apellidos: "Lopez", colonia: "Apartamento interinor 106" },
  { nombres: "janer", apellidos: "tarazona", colonia: "" },
  { nombres: "Sergio", apellidos: "Diaz Cuero", colonia: "Ciudadela confenalco etapa 4 apto 503 torre 5" },
  { nombres: "Tania", apellidos: "Curiel", colonia: "Casa" },
  { nombres: "Maik Angel", apellidos: "Galves", colonia: "" },
  { nombres: "Armando", apellidos: "Garcia", colonia: "Apartamento" },
  { nombres: "Jorge enrique", apellidos: "Mora valencia", colonia: "" },
  { nombres: "Julio Cesar", apellidos: "Camargo Corrales", colonia: "Casa" },
  { nombres: "Esneider", apellidos: "Bolívar acevedo", colonia: "Portería" },
  { nombres: "Hector", apellidos: "Aguilar", colonia: "Centro" },
  { nombres: "Jesús Armando", apellidos: "Ortiz", colonia: "Casa" },
  { nombres: "Rois", apellidos: "Dz", colonia: "Casa" },
  { nombres: "Esteban", apellidos: "coronado", colonia: "Casa" },
  { nombres: "Jhon jader", apellidos: "Ortiz caicedo", colonia: "Casa" },
  { nombres: "Jonathan Alejandro", apellidos: "Russi Machado", colonia: "Casa" },
  { nombres: "Virginia Paola", apellidos: "Cespedes Hurtado", colonia: "Casa" },
  { nombres: "Jeimmy", apellidos: "Bautista Pérez", colonia: "Casa" },
  { nombres: "Jeisson andres", apellidos: "Diaz", colonia: "Apartamento 201" },
  { nombres: "Marta", apellidos: "Coleone", colonia: "Apartamento" },
  { nombres: "Diego", apellidos: "Suárez", colonia: "Bodega 8" },
  { nombres: "Yilber Yesith", apellidos: "Medina Casanova", colonia: "Casa 13" },
  { nombres: "Valentina", apellidos: "Lopez", colonia: "Villamaria Caldas barrio la pradera" },
  { nombres: "Astrid", apellidos: "Moreno", colonia: "Almacen navegarepuestos" },
  { nombres: "Daniel", apellidos: "Romero", colonia: "Oficina interrapidicimo" },
  { nombres: "Luis Alfredo", apellidos: "Ospina García", colonia: "" },
  { nombres: "Jhon Sebastian", apellidos: "Luna Parada", colonia: "Módulo 3 Terminal Salitre" },
  { nombres: "Jeison Camilo", apellidos: "Jiménez rendon", colonia: "Casa" },
  { nombres: "Eric", apellidos: "Gonzalez Guzman", colonia: "Torre 7. Apto 1707" },
  { nombres: "Luis Fernando", apellidos: "Pinto Soraca", colonia: "Piso 1 apto 1" },
  { nombres: "Juan David", apellidos: "Fernandez Velasco", colonia: "Apartamento 103" },
  { nombres: "Miguel", apellidos: "Gonzalez", colonia: "Panadería jireth" },
  { nombres: "Sandra Milena", apellidos: "García", colonia: "" },
  { nombres: "Andres", apellidos: "Torres", colonia: "Agencia de viajes paraiso world" },
  { nombres: "Luis Eduardo", apellidos: "González mazuera", colonia: "" },
  { nombres: "CARLOS ALBERTO", apellidos: "CASTAÑO RAMIREZ", colonia: "" },
  { nombres: "Juan rafael", apellidos: "Herazo yepes", colonia: "Apartamento 1" },
  { nombres: "Cristian", apellidos: "Vargas", colonia: "Casa" },
  { nombres: "Marisol", apellidos: "Cardona", colonia: "" },
  { nombres: "Alexis Javier", apellidos: "Moreno marroquín", colonia: "Local" },
  { nombres: "Isaac", apellidos: "Castañeda lopera", colonia: "" },
  { nombres: "Mappi", apellidos: "Montero", colonia: "Apartamento 101" },
  { nombres: "Jonathan", apellidos: "Castañeda", colonia: "" },
  { nombres: "Geiler", apellidos: "Parra bernal", colonia: "Torre 5 apto 601" },
  { nombres: "Jeison", apellidos: "Pachón", colonia: "Última casa" },
  { nombres: "Alex", apellidos: "torres", colonia: "" },
  { nombres: "Williams", apellidos: "Herrera", colonia: "Casa" },
  { nombres: "Harry Antonio", apellidos: "Cuesta sanchez", colonia: "34B17" },
  { nombres: "Fabián", apellidos: "Ojeda", colonia: "" },
  { nombres: "Jeison", apellidos: "Araque", colonia: "Casa 64" },
  { nombres: "Diego Alexander", apellidos: "Pérez Velasquez", colonia: "Estación de Policía san pablo de borbur Boyacá" },
  { nombres: "yelitza", apellidos: "alvarado", colonia: "yelitzaa917@gmail.com" },
  { nombres: "MARTIN", apellidos: "LARGO", colonia: "Plánta Parmalat portería" },
  { nombres: "Omar", apellidos: "Garrido", colonia: "Casa" },
  { nombres: "Luis Eduardo", apellidos: "Garcia", colonia: "Casa" },
  { nombres: "Jonathan", apellidos: "Martinez Salazar", colonia: "" },
  { nombres: "Brenda sthefani", apellidos: "Gómez Burbano", colonia: "Oficina dirección de emprendimiento" },
  { nombres: "Jairo", apellidos: "Mendoza", colonia: "Casa Normal" },
  { nombres: "Jhont alexander", apellidos: "García suarez", colonia: "Piso 1" },
  { nombres: "EDINSON DE JESÚS", apellidos: "FLOREZ VASQUEZ", colonia: "Segundo piso" },
  { nombres: "Jose", apellidos: "Palencia", colonia: "Torre 10 401" },
  { nombres: "Ariel", apellidos: "Herrera", colonia: "Casa tercer piso" },
  { nombres: "Wilmer Andrés", apellidos: "Aguirre claros", colonia: "402" },
  { nombres: "Luis Fernando", apellidos: "Palmera month", colonia: "Local 1" },
  { nombres: "Johan Sebastián", apellidos: "Rincon", colonia: "" },
  { nombres: "José", apellidos: "failoc", colonia: "Casa" },
  { nombres: "Jhony", apellidos: "Rangel palencia", colonia: "" },
  { nombres: "Juan David", apellidos: "Rodriguez Ramos", colonia: "Segundo piso. Balcon de vidrios" },
  { nombres: "Richard", apellidos: "Vargas", colonia: "Entrada del congolo" },
  { nombres: "JOSE FRANCISCO", apellidos: "Medina Echeverry", colonia: "Casa" },
  { nombres: "Over", apellidos: "Bertel", colonia: "Casa" },
];

const GenerateColoniasExcel = () => {
  useEffect(() => {
    // Create workbook with the exact Dropi format
    const wb = XLSX.utils.book_new();
    
    // Create data array with headers matching Dropi format exactly
    const headers = [
      "NOMBRES",
      "APELLIDOS", 
      "DIRECCIÓN Y BARRIO",
      "DEPARTAMENTO",
      "CIUDAD",
      "TELÉFONO",
      "ID DE PRODUCTO",
      "CANTIDAD",
      "PRECIO TOTAL (SIN PUNTOS NI COMAS)",
      "CON RECAUDO",
      "NOTA",
      "EMAIL (OPCIONAL)",
      "ID DE VARIABLE (OPCIONAL)",
      "CODIGO POSTAL (OPCIONAL)",
      "TRANSPORTADORA (OPCIONAL)",
      "CEDULA (OPCIONAL)",
      "COLONIA (OBLIGATORIO SOLO PARA QUIKEN)",
      "SEGURO (SOLO APLICA PARA ENVIA)"
    ];
    
    const data = coloniasData.map(item => [
      item.nombres,
      item.apellidos,
      "", // DIRECCIÓN Y BARRIO
      "", // DEPARTAMENTO
      "", // CIUDAD
      "", // TELÉFONO
      "", // ID DE PRODUCTO
      "", // CANTIDAD
      "", // PRECIO TOTAL
      "", // CON RECAUDO
      "", // NOTA
      "", // EMAIL
      "", // ID DE VARIABLE
      "", // CODIGO POSTAL
      "", // TRANSPORTADORA
      "", // CEDULA
      item.colonia, // COLONIA
      "" // SEGURO
    ]);
    
    const wsData = [headers, ...data];
    const ws = XLSX.utils.aoa_to_sheet(wsData);
    
    // Set column widths
    ws['!cols'] = [
      { wch: 25 }, // NOMBRES
      { wch: 25 }, // APELLIDOS
      { wch: 40 }, // DIRECCIÓN
      { wch: 15 }, // DEPARTAMENTO
      { wch: 15 }, // CIUDAD
      { wch: 15 }, // TELÉFONO
      { wch: 15 }, // ID PRODUCTO
      { wch: 10 }, // CANTIDAD
      { wch: 20 }, // PRECIO
      { wch: 12 }, // CON RECAUDO
      { wch: 30 }, // NOTA
      { wch: 25 }, // EMAIL
      { wch: 20 }, // ID VARIABLE
      { wch: 15 }, // CODIGO POSTAL
      { wch: 20 }, // TRANSPORTADORA
      { wch: 15 }, // CEDULA
      { wch: 50 }, // COLONIA
      { wch: 15 }, // SEGURO
    ];
    
    XLSX.utils.book_append_sheet(wb, ws, "Colonias");
    
    // Download the file
    XLSX.writeFile(wb, "colonias_clientes.xlsx");
  }, []);

  return (
    <div className="min-h-screen flex items-center justify-center bg-background">
      <div className="text-center p-8">
        <h1 className="text-2xl font-bold mb-4">Gerando Excel...</h1>
        <p className="text-muted-foreground">O arquivo será baixado automaticamente.</p>
      </div>
    </div>
  );
};

export default GenerateColoniasExcel;
